import { ArrowRight, Brain, FileSearch, GraduationCap, MapPin, NotebookPen, Scale, Search, Trophy } from 'lucide-react';
import { Link } from 'wouter';
import { Shell } from '@/components/Shell';
import { cases } from '@/data/cases';
import { biases } from '@/data/biases';
import { fallacies } from '@/data/fallacies';

export default function City() {
  const xp = Number(localStorage.getItem('mindframe-xp') || '0');
  const completed: string[] = JSON.parse(localStorage.getItem('mindframe-completed') || '[]');
  const completedBiases: string[] = JSON.parse(localStorage.getItem('mindframe-bias-completed') || '[]');
  const completedFallacies: string[] = JSON.parse(localStorage.getItem('mindframe-fallacy-completed') || '[]');
  const unlocked = cases.filter((c) => c.unlocked || completed.includes(c.id)).length;
  return <Shell><div className="mf-page"><section className="mf-city-hero"><div><div className="mf-eyebrow">Night shift / 23:48</div><h1 className="mf-display">The city is<br /><em>still awake.</em></h1><p className="mf-lede">Welcome back, detective. The desk lamp is warm, the files are waiting, and somewhere in the city a story has been told incorrectly.</p></div><div className="mf-card mf-progress-card"><div className="mf-progress-number"><strong>{xp.toLocaleString()} XP</strong><span>Rank {xp > 500 ? 'Observer' : 'Rookie'}</span></div><div className="mf-progress"><span style={{ width: `${Math.min(100, (xp / 1200) * 100)}%` }} /></div><p className="mf-progress-caption">{completed.length} of 5 files closed · {unlocked} districts accessible</p></div></section>
    <div className="mf-section-head"><div><h2 className="mf-section-title">Choose your district</h2><p className="mf-section-copy">Every case is a different way of seeing.</p></div><Link href="/cases" className="mf-link" data-testid="link-all-cases">View all files <ArrowRight size={14} /></Link></div>
    <div className="mf-districts"><Link href="/cases" className="mf-district mf-district-link" data-testid="link-district-crime"><MapPin /><span>District 01</span><h3>Crime Scene</h3><p>You already spot lies in movies. Real suspects are harder — and way more satisfying to catch.</p></Link><Link href="/district/biases" className="mf-district mf-district-link mf-district-featured" data-testid="link-district-biases"><Brain /><span>District 02 / Complete</span><h3>Bias District</h3><p>Your brain cuts corners without asking you. Learn its favorite tricks before they cost you a case — or a real decision.</p><strong className="mf-district-action">Enter archive <ArrowRight size={13} /></strong></Link><Link href="/district/fallacies" className="mf-district mf-district-link mf-district-featured" data-testid="link-district-fallacies"><Scale /><span>District 03 / New</span><h3>Fallacy District</h3><p>Every bad argument you'll ever hear follows one of thirty patterns. Learn them once, spot them forever.</p><strong className="mf-district-action">Enter archive <ArrowRight size={13} /></strong></Link><div className="mf-district mf-district-locked"><GraduationCap /><span>District 04 / Locked</span><h3>Detective Academy</h3><p>Skip the theory-heavy textbook. Learn the same skills through cases that actually make you think.</p></div><div className="mf-district mf-district-locked"><Search /><span>District 05 / Locked</span><h3>Decision Lab</h3><p>This is where 'I would've caught that' gets tested. See how your snap judgments hold up.</p></div><div className="mf-district mf-district-locked"><FileSearch /><span>District 06 / Locked</span><h3>Argument Analyzer</h3><p>Got a real argument you're stuck on — an email, a debate, a headline? Drop it in and see what's actually wrong with it.</p></div><div className="mf-district mf-district-locked"><NotebookPen /><span>District 07 / Locked</span><h3>Mind Palace</h3><p>Knowing a bias once isn't the same as remembering it when it matters. This is how you make it stick.</p></div><div className="mf-district mf-district-locked"><Trophy /><span>District 08 / Locked</span><h3>Achievements</h3><p>Every case cracked is a bias you won't fall for again. Track how far you've come.</p></div></div>
    <div className="mf-section-head"><div><h2 className="mf-section-title">Your field notes</h2><p className="mf-section-copy">A small record of the work.</p></div></div>
    <div className="mf-stat-grid"><div className="mf-stat"><span className="mf-stat-value">{completed.length}</span><span className="mf-stat-label">Files closed</span></div><div className="mf-stat"><span className="mf-stat-value">{xp}</span><span className="mf-stat-label">Experience</span></div><div className="mf-stat"><span className="mf-stat-value">{completedBiases.length}<small> / {biases.length}</small></span><span className="mf-stat-label">Biases catalogued</span></div><div className="mf-stat"><span className="mf-stat-value">{completedFallacies.length}<small> / {fallacies.length}</small></span><span className="mf-stat-label">Fallacies catalogued</span></div></div>
  </div></Shell>;
}